services:
  novel-crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: novel-crawler
    environment:
      NOVELS: ""
    volumes:
      # Persist outputs and cached cover/assets to your host
      - ./books:/app/books
      - ./assets:/app/assets
#      - ./novels.txt:/app/novels.txt
    restart: "unless-stopped"

